require("dylanhand.plugins-setup")
require("dylanhand.core.options")
require("dylanhand.core.keymaps")
require("dylanhand.core.colorscheme")
require("dylanhand.core.autocommands")
require("dylanhand.plugins.autopairs")
require("dylanhand.plugins.comment")
require("dylanhand.plugins.nvim-tree")
require("dylanhand.plugins.nvim-cmp")
require("dylanhand.plugins.lualine")
require("dylanhand.plugins.gitsigns")
require("dylanhand.plugins.telescope")
require("dylanhand.plugins.treesitter")
require("dylanhand.plugins.lsp.mason")
-- require("dylanhand.plugins.lsp.lspsaga")
require("dylanhand.plugins.lsp.lspconfig")
